### ISSUE TITLE
Is saving plain auth in local storage secure?

### ISSUE THREAD

**Issue by rrevanth** [ryanswapp/elixir-react-redux-example#2]
Can this be used in a production app?

Since storing jwt auth plain in localstorage is not secure.If we want to use it in a production app.what do we need to change here?

**Comment by ryanswapp** [comment]
Your two options are either store the JWT in local/session storage or put it in a cookie. Both have their advantages/disadvantages and neither is a silver bullet. Storing the plain jwt is secure as long as you don't store confidential information in it. If you do want to store confidential information then you should encrypt the contents of the JWT before signing it on the server side.

**Comment by rrevanth** [comment]
Thank you.
That clears part of my question. What I observed in guardian is that jwt token does not expire even if user logout.That issue was explained and fixed by the developer himself with guardian db.

Also,can you explain or direct me to a article explaining pros and cons of storing in session/local vs in a cookie?
